In [2]:
import krippendorff

import pandas as pd
import numpy as np

In [85]:
df = pd.read_csv('data/group_16_ratings.csv')
raw_data = pd.read_csv('data/si630w22-hw3-data.csv')

In [8]:
df.columns

Index(['id', 'annotator', 'rating'], dtype='object')

In [9]:
df.head(3)

id annotator  rating
0  gwi9ij1  hjmccabe       4
1  gwi9ij1   ccmilne       4
2  gwig0uu  hjmccabe       4

### Inter-Annotator Agreement Analysis

- Cam vs. Harrison
- Cam + Harrison vs. others

In [63]:
user1 = df[df['annotator'] == 'hjmccabe']
user2 = df[df['annotator'] == 'ccmilne']

merged = user1.merge(user2, left_on='id', right_on='id')

user1_ratings = list(merged['rating_x'])
user2_ratings = list(merged['rating_y'])

r_data = np.column_stack((user1_ratings, user2_ratings)).T

array([4, 4, 2, 5, 4, 3, 4, 5, 3, 2, 3, 3, 5, 1, 2, 2, 3, 3, 4, 1, 2, 3,
       4, 3, 4, 5, 5, 5, 4, 5, 2, 1, 4, 2, 2, 3, 4, 3, 1, 2, 3, 5, 5, 4,
       1, 4, 5, 3, 3, 5, 4, 4, 3, 4, 5, 4, 5, 4, 3, 5, 2, 4, 1, 4, 2, 4,
       3, 4, 3, 4, 3, 4, 5, 5, 4, 5, 4, 5, 4, 4, 4, 5, 4, 3, 4, 5, 3, 4,
       1, 2, 5, 2, 1, 5, 5, 4, 1, 3, 4, 5, 4, 5, 3, 3, 4, 5, 5, 5, 5, 5,
       3, 5, 4, 4, 2, 4, 5, 4, 1, 4, 5, 1, 1, 5, 1, 1, 3, 3, 2, 4, 3, 4,
       1, 5, 4, 4, 1, 5, 4, 4, 5, 2, 5, 1, 3, 5, 3, 3, 3, 2, 5, 5, 1, 4,
       5, 5, 5, 2, 4, 3, 3, 3, 3, 4, 5, 5, 5, 5, 3, 3, 4, 3, 4, 5, 2, 5,
       4, 5, 5, 4, 3, 4, 1, 3, 3, 5, 4, 4, 3, 3, 4, 3, 2, 3, 4, 2, 4, 3,
       1, 3, 4, 5, 5, 5, 5, 5, 4, 2, 5, 3, 3, 4, 5, 5, 4, 2, 4, 3, 3, 3,
       3, 5, 1, 4, 5, 4, 3, 3, 4, 2, 5, 3, 5, 3, 2, 2, 4, 4, 4, 5, 2, 4,
       5, 4, 4, 4, 4, 4, 2, 5, 5, 3, 5, 2, 3, 3, 3, 4, 1, 4, 5, 3, 5, 3,
       5, 5, 5, 3, 4, 4, 3, 5, 5, 1, 4, 2, 5, 4, 5, 4, 4, 4, 3, 5, 5, 2,
       5, 3, 4, 5, 3, 4, 5, 2, 2, 5, 3, 4, 5, 5, 4,

In [64]:
#Pearson Score
np.corrcoef(r_data[0], r_data[1])

array([[1.       , 0.5263582],
       [0.5263582, 1.       ]])

In [61]:
krippendorff.alpha(reliability_data=r_data, level_of_measurement='nominal')

0.18664908364962074

In [36]:
r_data

array([[4., 4., 4., ..., 4., 4., 4.],
       [5., 5., 5., ..., 5., 5., 5.]])

In [62]:
krippendorff.alpha(reliability_data=r_data, level_of_measurement='ordinal')

0.4604470426662728

##### Group 16 vs. Class

In [56]:
df = pd.read_csv('data/si630w22-hw3-train.csv')

In [57]:
g16 = df[df['group'] == 'group_16']
unique_ids = set(g16['id'])
print(len(df))
print(len(unique_ids))

un_df = df[df['id'].isin(unique_ids)]

print(len(un_df))
un_df['group'].value_counts()

17845
295
1281


group_16    590
group_20     48
group_22     42
group_10     39
group_12     39
group_07     36
group_09     33
group_18     33
group_24     33
group_21     32
group_08     30
group_02     30
group_03     30
group_25     30
group_17     27
group_01     26
group_05     26
group_04     24
group_14     24
group_19     22
group_15     22
group_13     22
group_23     22
group_11     21
Name: group, dtype: int64

In [71]:
avgs = un_df.groupby(by=['id', 'group']).mean()

avgs.reset_index(inplace=True)
avgs

avgs[avgs['id'] == 't3_n28tgd']

df = avgs

In [72]:
g16   = df[df['group'] == 'group_16']
other = df[df['group'] != 'group_16']

print(len(g16))
print(len(other))

merged = g16.merge(other, left_on='id', right_on='id')
print(len(merged))


g16_ratings = list(merged['rating_x'])
other_ratings = list(merged['rating_y'])

r_data = np.column_stack((g16_ratings, other_ratings)).T

295
282
282


In [69]:
r_data

array([[4. , 3.5, 2.5, 4.5, 3.5, 4. , 2.5, 2.5, 4.5, 1. , 2. , 1.5, 4. ,
        2.5, 3. , 3. , 1.5, 2. , 3.5, 4.5, 3.5, 3. , 1.5, 4.5, 2.5, 2. ,
        3.5, 3.5, 4. , 4. , 4.5, 1.5, 2. , 3.5, 2. , 3.5, 4.5, 3.5, 4. ,
        4.5, 4. , 4. , 1.5, 4. , 3. , 3.5, 4. , 3. , 3. , 4. , 5. , 4. ,
        4. , 4. , 4. , 4. , 3. , 3.5, 4. , 3. , 1.5, 4. , 1. , 1.5, 4. ,
        4. , 2.5, 4. , 1. , 4. , 4. , 4. , 3. , 3. , 4.5, 4. , 3. , 3.5,
        4. , 5. , 2. , 4.5, 2. , 3. , 2.5, 4. , 5. , 1.5, 3.5, 2. , 4. ,
        3.5, 5. , 2. , 3.5, 4.5, 5. , 3. , 3. , 4.5, 1. , 4.5, 4. , 4. ,
        4. , 2.5, 3. , 3. , 4. , 3. , 3. , 4. , 3.5, 4.5, 2. , 4.5, 4. ,
        4. , 4. , 4.5, 3. , 2. , 4. , 4. , 4. , 3.5, 2.5, 3.5, 3.5, 3. ,
        3. , 3. , 3.5, 1.5, 3. , 4.5, 4.5, 4.5, 4.5, 4. , 4.5, 4.5, 2.5,
        3. , 4. , 1.5, 3.5, 3. , 2. , 1.5, 5. , 3.5, 3. , 3.5, 4.5, 4. ,
        4. , 3. , 2.5, 3.5, 3.5, 4.5, 2.5, 4. , 4.5, 3.5, 3.5, 4. , 2.5,
        4.5, 5. , 3. , 4. , 3. , 3.5, 3. , 4. , 3. 

In [73]:
np.corrcoef(r_data[0], r_data[1])

array([[1.        , 0.60271672],
       [0.60271672, 1.        ]])

In [75]:
krippendorff.alpha(reliability_data=r_data, level_of_measurement='nominal')

0.10581615126449018

In [74]:
krippendorff.alpha(reliability_data=r_data, level_of_measurement='ordinal')

0.5257040193529188

In [68]:
df['group'].value_counts()

group_16    295
group_20     16
group_21     16
group_03     15
group_08     15
group_25     15
group_22     14
group_01     13
group_05     13
group_10     13
group_12     13
group_04     12
group_07     12
group_14     12
group_09     11
group_24     11
group_18     11
group_19     11
group_15     11
group_13     11
group_23     11
group_02     10
group_17      9
group_11      7
Name: group, dtype: int64

In [79]:
merged

id   group_x  rating_x   group_y  rating_y      diff
0    t3_n28tgd  group_16       4.0  group_01  5.000000  1.000000
1    t3_n2bvbq  group_16       3.5  group_02  4.666667  1.166667
2    t3_n2fc4o  group_16       2.5  group_03  3.000000  0.500000
3    t3_n2jtaz  group_16       4.5  group_04  4.000000  0.500000
4    t3_n2mblk  group_16       3.5  group_05  5.000000  1.500000
..         ...       ...       ...       ...       ...       ...
277  t3_npa60b  group_16       4.0  group_17  5.000000  1.000000
278  t3_npadrz  group_16       2.5  group_19  3.500000  1.000000
279  t3_npam82  group_16       5.0  group_25  5.000000  0.000000
280  t3_npazqx  group_16       4.0  group_23  5.000000  1.000000
281  t3_npazv0  group_16       4.5  group_24  5.000000  0.500000

[282 rows x 6 columns]

In [78]:
merged['diff'] = abs(merged['rating_x'] - merged['rating_y'])

In [97]:
top10 = merged.sort_values(by='diff', ascending=False)[:10]
top10

top10ids = list(top10['id'])
top10

id   group_x  rating_x   group_y  rating_y      diff
216  t3_nk43wu  group_16       4.0  group_13  1.000000  3.000000
16   t3_n3e4qy  group_16       1.5  group_25  4.000000  2.500000
6    t3_n30alr  group_16       2.5  group_10  5.000000  2.500000
275  t3_np7sub  group_16       2.5  group_21  5.000000  2.500000
68   t3_n7ibs2  group_16       1.0  group_02  3.333333  2.333333
213  t3_njnbfz  group_16       2.0  group_05  4.000000  2.000000
22   t3_n47tg7  group_16       1.5  group_08  3.500000  2.000000
17   t3_n3e5dy  group_16       2.0  group_24  4.000000  2.000000
148  t3_ne6faj  group_16       2.0  group_05  4.000000  2.000000
130  t3_ncq2s1  group_16       3.0  group_03  5.000000  2.000000

In [96]:
t10 = raw_data[raw_data['question_id'].isin(top10ids)]
list(t10.question_text)
list(t10.reply_text)
t10

question_id                                      question_text reply_id  \
1144   t3_nk43wu  [Epic Rap Battles of History] How do the conte...  gzc7ia8   
1274   t3_n47tg7  Now that Bill and Melinda Gates are both singl...  gwtyh4z   
1989   t3_n30alr  What is the best birthday present you've ever ...  gwmp9gv   
3253   t3_n3e5dy  You have been given a superpower of your choos...  gwpaas2   
3254   t3_n3e4qy                         How to deal with jealousy?  gwpafi3   
3301   t3_n7ibs2  What’s the best comeback to an insult you’ve e...  gxcz0l6   
3362   t3_ncq2s1  ELI5: Why are people not visible in Google Map...  gy6j6gj   
3379   t3_ne6faj  What is the best "Your mama....." joke you hav...  gyexlym   
3439   t3_njnbfz  What are some things you can do, to keep peopl...  gz8bdjj   
3505   t3_np7sub  What's something your gender does that the opp...  h03z93m   

                                             reply_text  rlen  
1144  Not only that, most of the contestants lived b...   380  
1274                             Huh? Did they divorce?    22  
1989                      Railroad shirt and phone case    29  
3253  The ability to extend other peoples power time...    75  
3254  Your girlfriend is never going to meet Billie ...   363  
3301                        *Your mom goes to college.*    27  
3362  Any large scale map will be made up of many in...   531  
3379  Your momma is so ugly Helen Keller committed s...    52  
3439  Ask them questions, reflective listening, idk man    49  
3505  Three things you should know about boners: * H...   423