## SI 670 Applied Machine Learning, Assignment 1 (Part 1):
## NumPy Exercises (30 pts).   Due Thursday Sept 16 2021, 12:59pm.


Submit your completed notebook file to the Canvas site - IMPORTANT: please name your submitted file si670-hw1-part1-youruniqname.ipynb.

As a reminder, the notebook code you submit must be your own work. Feel free to discuss general approaches to the homework with classmates.

The [NumPy](https://numpy.org/) library and its n-dimensional arrays in particular are indispensable to applied machine learning in Python, as many popular machine learning libraries, such as [Scikit-Learn](https://scikit-learn.org/stable/), are built on top of NumPy. Having a strong command of NumPy serves as a great stepping stone into the exciting world of applied machine learning. The purpose of this assignment is to help you review and practice some of the common operations and coding patterns associated with `np.ndarray` objects. 

In [1]:
# Since this is a NumPy exercise, please use NumPy as the only external library in your work
import numpy as np

### Question 1. Array Creation (5 pts)

Write a function to create an `n` by `d` `np.ndarray` of an integer type with numbers from `0` to `k` (exclusive) filled in. The numbers should be aranged in order and along the rows. For example, with `k=100`, `n=20` and `d=5`, your function should return:

```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       ...
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])
```

**This function should return an integer `np.ndarray` of shape `(n, d)`.**

In [49]:
def create_array(k, n, d):
    """
    This function returns an n by d matrix with numbers from 0 to k (exclusive) filled in. 
    """
    assert n * d == k, "Q1: The values of n and d are not compatible with the value of k. "
    
    array = np.arange(k).reshape((n, d))
    
    return array

In [50]:
#testing
q1 = create_array(k=100, n=20, d=5)
print(q1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


### Question 2. Row Sum (5 pts)

Complete the function below that returns the sum of all **rows** in a 2-D matrix as a **row** vector. For example, given matrix

```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       ...
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])
```

it should return
```
array([ 950,  970,  990, 1010, 1030])
```

**This function should return a `np.ndarray` of shape `(arr.shape[-1], )`, given the input 2D matrix `arr`.**

In [51]:
def calc_row_sum(arr):
    """
    This function calculates the sum of all rows in a 2D matrix "arr". 
    """
    row_sum = arr.sum(axis=0)
    
    return row_sum

In [52]:
q2 = calc_row_sum(q1)
print(q2)

[ 950  970  990 1010 1030]


### Question 3. Column Sum (5 pts)

Complete the function below that returns the sum of all **columns** in a 2-D matrix as a **column** vector. For example, given matrix

```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       ...
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])
```

it should return
```
array([[ 10],
       [ 35],
       ...
       [460],
       [485]])
```

**This function should return a `np.ndarray` of shape `(arr.shape[0], 1)`, given the input 2D matrix `arr`.**

In [53]:
def calc_col_sum(arr):
    """
    This function calculates the sum of all columns in a 2D matrix "arr". 
    """
    col_sum = arr.sum(axis=1)
    
    return col_sum

In [54]:
q3 = calc_col_sum(q1)
print(q3)

[ 10  35  60  85 110 135 160 185 210 235 260 285 310 335 360 385 410 435
 460 485]


### Question 4. Sum of Entries from Even Rows and Columns  (5 pts)

Write a function to return the sum of entries with **an even row and column index** in a 2-D matrix as a **single number**. For example, given matrix

```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])
```

it should return `6`, because `6 = 0 + 2 + 4`. 

**This function should return a single number given the input 2D matrix `arr`.**

In [55]:
def calc_even_row_col_sum(arr):
    """
    This function calculates the sum of entries with an even row and column index
    """
    even_row_col_sum = arr[0::2, 0::2].sum()
    
    return even_row_col_sum

In [56]:
arr = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
q4 = calc_even_row_col_sum(arr)
print(q4)

6


In [57]:
test=create_array(100,20,5)
calc_even_row_col_sum(test)

1410

### Question 5. Row Selection  (5 pts)

Write a function to return the `top_n` **rows** of a 2-D matrix in descending order of their sum of entries. For example, given matrix

```
array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5],
       [24, 25, 26, 27, 28, 29]])
```

and `top_n=3`, it should return
```
array([[24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17]])
```

**This function should return a `np.ndarray` of shape `(top_n, arr.shape[-1])`, given the input 2D matrix `arr`.**

In [58]:
def select_rows(arr, top_n):
    """
    This function selects the top_n rows that have the largest sum of entries
    """
    sorted_matrix = arr[np.argsort(arr.sum(axis=1))][::-1]  
    sel_rows = sorted_matrix[0:top_n]

    return sel_rows

In [59]:
arr = np.array([[ 6,  7,  8,  9, 10, 11],
               [12, 13, 14, 15, 16, 17],
               [18, 19, 20, 21, 22, 23],
               [ 0,  1,  2,  3,  4,  5],
               [24, 25, 26, 27, 28, 29]])

q5 = select_rows(arr, top_n=3)
print(q5)

[[24 25 26 27 28 29]
 [18 19 20 21 22 23]
 [12 13 14 15 16 17]]


### Question 6. Pairwise Cosine Similarity  (5 pts)

Write a function to compute all pairwise cosine similarity of the **row vectors** in a 2-D matrix. For example, given matrix

```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
```

it should return
```
array([[1.        , 0.91465912, 0.87845859],
       [0.91465912, 1.        , 0.99663684],
       [0.87845859, 0.99663684, 1.        ]])
```

where the `(i, j)` entry of the result is the cosine similarity between the row vector `arr[i]` and the row vector `arr[j]`:  

```
cos_sim[i, j] == CosSim(arr[i], arr[j]).
```



As usual, the cosine similarity between two vectors $x, y$ is defined as:

\begin{equation*}
\mathrm{CosSim}(x, y) = \frac{x^{T}y}{\left\lVert x \right\rVert_{2} \left\lVert y \right\rVert_{2}} = \left(\frac{x}{\left\lVert x \right\rVert_{2}}\right)^{T}\left(\frac{y}{\left\lVert y \right\rVert_{2}}\right)
\end{equation*}

**This function should return a `np.ndarray` of shape `(arr.shape[0], arr.shape[0])`, given the input 2D matrix `arr`.**

In [4]:
def calc_pairwise_cos_sim(arr):
    """
    This function computes all pairwise cosine similarity
    """   
    reshaped = arr / np.linalg.norm(arr, 2, axis=1).reshape(-1, 1)
    #print(reshaped)
    cos_sim = np.dot(reshaped, reshaped.T)
        
    return cos_sim

In [5]:
arr = np.array([[ 0,  1,  2,  3,  4],
                [ 5,  6,  7,  8,  9],
                [10, 11, 12, 13, 14]])

q6 = calc_pairwise_cos_sim(arr)
print(q6)

[[1.         0.91465912 0.87845859]
 [0.91465912 1.         0.99663684]
 [0.87845859 0.99663684 1.        ]]


While this "appetiser" exercise cannot possibly cover all aspects of NumPy, we do hope it has helped you identify your own areas of improvement and stimulated your "appetite" for practising NumPy more!